//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : controller.hpp
//  @ Date : 16/04/2010
//  @ Author :
//
//


#if !defined(_CONTROLLER_HPP)
#define _CONTROLLER_HPP

#include "snake.hpp"

class Snake;
class Controller {
public:

   virtual int change_direction(int x,int y, int z)=0;
   void Initialise(Snake* thesnake)
{

    _thesnake = thesnake;


}
    Snake* _thesnake;
};

#endif  //_CONTROLLER_HPP
