//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : playercontroller.hpp
//  @ Date : 16/04/2010
//  @ Author :
//
//


#if !defined(_PLAYERCONTROLLER_HPP)
#define _PLAYERCONTROLLER_HPP

#include "Controller.hpp"
#include <prg/app.hpp>

class PlayerController : public Controller {
    public:

    int change_direction(int x, int y, int z)
    {
        if (z == 1 && _thesnake->direction_ != 2){ _thesnake->direction_ =1;}
        if (z == 2 && _thesnake->direction_ != 1){ _thesnake->direction_ =2;}
        if (z == 3 && _thesnake->direction_ != 4){ _thesnake->direction_ =3;}
        if (z == 4 && _thesnake->direction_ != 3){ _thesnake->direction_ =4;}
        if (z == 0){ _thesnake->direction_ =0;}

        return _thesnake->direction_;
    }
};

#endif  //_PLAYERCONTROLLER_HPP
